#!/bin/bash

# Initialize a mongo data folder and logfile
mkdir -p /data/db
touch /var/log/mongodb.log
chmod 777 /var/log/mongodb.log

# Start mongodb with logging
# --logpath    Without this mongod will output all log information to the standard output.
# --logappend  Ensure mongod appends new entries to the end of the logfile. We create it first so that the below tail always finds something
/entrypoint.sh mongod --logpath /var/log/mongodb.log --logappend &

# Wait until mongo logs that it's ready (or timeout after 60s)
COUNTER=0
grep -q 'waiting for connections on port' /var/log/mongodb.log
while [[ $? -ne 0 && $COUNTER -lt 60 ]] ; do
    sleep 2
    let COUNTER+=2
    grep -q 'waiting for connections on port' /var/log/mongodb.log
done

# Check dump directory isn't empty
if [ -z "$(ls -A /mongodump)" ]; then
   echo "No backup to restore"
   exit 2
fi

# Restore from dump
if ( ! /usr/bin/mongorestore --quiet /mongodump ); then
    echo "Failed to restore backup"
    exit 1
fi

